plugins {
    id 'com.android.library'
}

android {
    namespace = "com.android.settingslib.widget.preference.slider"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src")
            kotlin.directories.addAll(["src"])
            res.srcDirs("res")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

}

dependencies {
    api project(':SettingsLib:Preference')
    api project(':SettingsLib:SettingsTheme')
    implementation(libs.annotation)
    implementation(libs.androidx.preference)
}
