plugins {
    id 'com.android.library'
}

android {
    def (sdkMajor, sdkMinor) = COMPILE_SDK.tokenize('.')
    compileSdk {
        version = sdkMinor ? release(sdkMajor as int) { it.minorApiLevel = sdkMinor as int } : release(sdkMajor as int)
    }

    namespace = "com.android.systemui.plugin_core"

    defaultConfig {
        minSdk = 26
        targetSdk = 36
        versionCode 1
        versionName "1.0"
    }
    buildFeatures {
        aidl = true
    }
    sourceSets {
        main {
            java.srcDirs = ['src']
            aidl.srcDirs = ['src']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}
