plugins {
    id 'com.android.library'
//    alias(libs.plugins.google.protobuf)
}

android {
    buildToolsVersion "37.0.0"
    namespace "app.lawnchair.compatlib"
    compileSdk 36

    defaultConfig {
        minSdk = 26
    }

    buildFeatures {
        aidl true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    sourceSets {
        main {
            aidl.srcDirs = ['src/main/java']
//            proto {
//                srcDirs = ['src/main/java']
//            }
        }
    }
}
