title: Murine Launcher
description: >-
  A modern, lightweight FOSS Android Launcher delivering an enhanced stock Android
  experience with essential customization and zero bloat.
url: "https://alesimula.github.io"
baseurl: ""

github_repo: "alesimula/Murine-launcher"
icon_url: "https://raw.githubusercontent.com/alesimula/Murine-launcher/refs/heads/main/image/app_icon/icon_browser_fullsize.svg"
screenshots_api: "https://api.github.com/repos/alesimula/Murine-launcher/contents/fastlane/metadata/android/en-US/images/phoneScreenshots"
releases_api: "https://api.github.com/repos/alesimula/Murine-launcher/releases"

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
